---
title: Levered Life
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Levered Life
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed
gems:
- jekyll-paginate
paginate: 3
paginate_path: "/page/:num"
