---
title: Levered Life
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: All things smart home, home automation, and digital integration
name: Levered Life
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed
gems:
- jekyll-paginate
paginate: 2
paginate_path: "/page/:num"
